### ISSUE TITLE
react-error-boundary

### ISSUE THREAD

**Issue by Savvy** [Zaydme/strapi-plugin-multi-select#2] opened 2022-11-22 22:17 UTC
Can not create new entries after installing
![image](https://user-images.githubusercontent.com/20020849/203432548-19d09338-9d28-4069-a147-699bdd0a9bc2.png)

**Comment by itecom-artdesign** [comment] 2022-11-24 15:14
Same here. 
Strapi 4.5.1 and 4.5.2

To provide more input: 

I can edit already created documents before install, but when I try to create new entries I got a blank page. 
Same both locally and in production.

**Comment by Zaydme** [comment] 2022-11-24 16:13
Thank you for your report
Could you please try the new version `1.1.0` which hopefully fixes this since I was unable to reproduce.
if yes we can close this issue!

**Comment by itecom-artdesign** [comment] 2022-11-24 23:27
Fixed the issue for me, thanks a lot for your work and reactivity <3

**Comment by dmarkbreiter** [comment] 2023-03-15 18:39
@Zaydme, I have a similar issue as detailed here using version `1.1.0` on Strapi 4.6.

**Comment by Zaydme** [comment] 2023-07-16 13:03
Fixed with **feat: replace strapi select with react-select** https://github.com/Zaydme/strapi-plugin-multi-select/pull/14

Please update to next release which will be **1.2.0**

**Closed as completed by Zaydme** 2023-07-16 13:03 UTC
Labels: bug
